fragment ApplicationListFragment on Application {
  id
  name
  updatedAt
  collaborators {
    ...UserFragment
    ...on ApplicationCollaboratorGroup {
      id
      name
      members{
        ...UserFragment
      }
    }
  }
}